# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
  FILE: ./src/index.md
interval: 500ms
tasks:
  exit:
    cmds:
      - exit
    silent: true
  dev:
    watch: true
    cmds:
      - cp ./src/header.html ./static/index.html
      - cmark -t html {{.FILE}} >> ./static/index.html
    sources:
      - ./src/index.md
    generates:
      - ./static/index.html
  build:
    # watch: true
    cmds:
      - cp ./src/header.html ./static/index.html
      - cmark --unsafe -t html {{.FILE}} >> ./static/index.html
    sources:
      - ./src/index.md
    generates:
      - index.html
  default:
    cmds:
      - task $(cat Taskfile.yml | yq '.tasks | keys | .[]' | fzf --height 50% )
    silent: true
