# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
  FILE: ./src/index.md
  OUTPUT: ./static/index.html
interval: 500ms
tasks:
  exit:
    cmds:
      - exit
    silent: true
  build:
    cmds:
      - cp ./src/header.html {{.OUTPUT}}
      - echo "<title>$(cat src/index.md | grep '^# ' | awk '{print $2}')</title>" >> {{.OUTPUT}}
      - echo "</head><body><container>" >> {{.OUTPUT}}
      - cmark --unsafe -t html {{.FILE}} >> {{.OUTPUT}}
      - echo "</container></body></html>" >> {{.OUTPUT}}
    sources:
      - ./src/index.md
    generates:
      - '{{.OUTPUT}}'
  dev:
    watch: true
    cmds:
      - task build
    sources:
      - ./src/index.md
    generates:
      - '{{.OUTPUT}}'
  default:
    cmds:
      - task $(cat Taskfile.yml | yq '.tasks | keys | .[]' | fzf --height 50% )
    silent: true
